### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by phoenix-bjoern** [fruitcake/magento2-custom-image-url#1]
First: Thank you for your wonderful module!

Although the module is released with the version 1.0.0 in `composer.json` it is still considered as development version and requires `minimum-stability: dev` in your project`s  `composer.json` in order to install it.

Please create a tag 1.0.0 in the Github repo. This will change the version on Packagist (https://packagist.org/packages/fruitcake/magento2-custom-image-url) and Composer will consider it as a stable version.

**Comment by Tjitse-E** [comment]
@barryvdh could you release the first version?

**Comment by barryvdh** [comment]
Yes tagged https://github.com/fruitcake/magento2-custom-image-url/releases/tag/v0.1.0
